---
- name: Set Resolution in Grub
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash'
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet splash video=hyperv_fb:{{ hyper_v_resolution }}"
  register: grub_file

- name: Update Grub, if changed
  become: true
  ansible.builtin.command: update-grub
  when: grub_file.changed
  tags: ['skip_ansible_lint']
