---
code_executable: "/snap/bin/code"
code_extensions:
  ## Ansible, Docker-Compose, etc.
  - redhat.vscode-yaml

  ## Jupyter
  - ms-toolsai.jupyter

  ## Terraform
  - hashicorp.terraform

  ## Docker and Remote Development
  - ms-azuretools.vscode-docker
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  # - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack

  ## General Development
  - christian-kohler.path-intellisense
  - vscode-icons-team.vscode-icons
  - riccardoNovaglia.missinglineendoffile
  - shardulm94.trailing-spaces
  # - Shan.code-settings-sync

  ## Git Utilities
  - eamodio.gitlens
  - donjayamanne.githistory
  - mhutchie.git-graph

  ## Markdown Linting
  - DavidAnson.vscode-markdownlint

  ## Python Development
  - ms-python.python
  - himanoa.Python-autopep8
  - njpwerner.autodocstring
  - wholroyd.jinja
  # Pyright Attribution to tiangolo and florimondmanca
  # https://twitter.com/tiangolo/status/1252891149708275713?s=21
  # > Disabled type checking in the extension settings as I rely on mypy,
  # > but autoimport and unused import colouring alone make it a
  # > 100% worthwhile companion on VSCode
  - ms-pyright.pyright
  - ms-python.vscode-pylance

  ## Spellchecking
  - streetsidesoftware.code-spell-checker

  ## Themes
  - sdras.night-owl

  ## Travis-CI
  # - felixrieseberg.vsc-travis-ci-status # has issues with status resolution

  ## Vue.js Development
  - octref.vetur
  - dbaeumer.vscode-eslint
  - pranaygp.vscode-css-peek
  - sdras.vue-vscode-snippets

docker_compose_version: 1.29.2

# nautilus_mounts:
#   - mount: "folder"
#     unc_path: "\\\\server\\folder\\"  # escaped slashes

flatpak_applications:
  - "com.giuspen.cherrytree" # Hierarchical Note Taking
  - "com.uploadedlobster.peek" # Simple screen recorder with an easy to use interface
  - "com.github.junrrein.PDFSlicer"
  - "com.spotify.Client" # Music
  - "com.rafaelmardojai.Blanket" # Background Sounds
  - "com.github.tchx84.Flatseal" # Manage Flatpak permissions
  - "org.gabmus.whatip" # Info on your IP
  - "com.bitwarden.desktop" # A secure and free password manager for all of your devices
  # - "com.github.alainm23.planner" # Never worry about forgetting things again (Todoist sync too)
  #- "org.libreoffice.LibreOffice"


nodejs_version: "14.x"
nodejs_npm_global_packages:
  - name: "yarn"

# Set to true to suppress the UID/GID switching when running package scripts. If
# set explicitly to false, then installing as a non-root user will fail.
npm_config_unsafe_perm: "true"

snaps:
  - name: "authy" # 2-Factor Authentication
  - name: "beekeeper-studio" # An open source SQL editor and database management app
  - name: "flameshot" # Powerful yet simple to use screenshot software
  - name: "slack"
    classic: "yes"
  - name: "chromium"
  # - name: "firefox" # Using deb until gnome-extensions installations work with firefox snap
snaps_plugs:
  - plug: "home"
    app: "chromium"

stacer_version: 1.1.0

yadm_dotfiles_repo: "https://github.com/icancclearynow/dotfiles"
yadm_dotfiles_branch: "main"

# https://github.com/icancclearynow/ansible-role-zsh
zsh_theme: robbyrussell
zsh_custom_shell_command: "false"
# useful when users are bound to external systems (i.e. active directory)
# zsh_custom_shell_command: "true"
# zsh_default_shell_command: "/opt/pbis/bin/config LoginShellTemplate /usr/bin/zsh"
zsh_aliases:
  # https://opensource.com/article/19/7/bash-aliases
  # - ls='ls -F'
  # - ll='ls -lh'
  - ls="colorls"
  - mnt="mount | awk -F' ' '{ printf \"%s\t%s\n\",\$1,\$3; }' | column -t | egrep ^/dev/ | sort"
  - hg='history|grep' # search bash history
  - left='ls -t -1' # most recently edited files
  - cg='cd `git rev-parse --show-toplevel`' # go to git main level
  - full-upgrade='sudo apt update && sudo apt full-upgrade -y && sudo apt autoremove -y'

ohmyzsh_bundles:
  # Bundles from the default repo (robbyrussell's oh-my-zsh) only need a name
  # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
  #
  # `name` is required (any valid file name will do so long as it's unique for the bundles)
  # `url` is git username/repo
  # `version` is git release and is required if `url` is define
  # - name: ansible
  # - name: aws
  # - name: docker
  # - name: docker-compose
  - name: gitfast
  # - name: pipenv
  - name: yarn
  # Syntax highlighting bundle.
  - name: 'zsh-syntax-highlighting'
    git:
      user: zsh-users
      repo: zsh-syntax-highlighting
      version: 0.7.1
  # # Autosuggestions
  # - name: zsh-autosuggestions # `name` is required (any valid file name will do so long as it's unique for the bundles)
  #   repo:
  #     user: zsh-users
  #     repo: zsh-autosuggestions
  #     version: v0.6.4
  - name: powerlevel10k
    skip_zshrc_plugin:
    git:
      user: romkatv
      repo: powerlevel10k
      version: v1.15.0
