---
- hosts: desktop
  # connection: local
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
    - name: Massage ansible_distribution_release for elementary OS 6.x
      set_fact:
        ansible_distribution_release: focal
      when: ansible_distribution_release in ["odin", "jolnir"]
      register: elementary_os
      tags: ['always']
    - name: Massage ansible_distribution_release for elementary OS 7.x
      set_fact:
        ansible_distribution_release: jammy
      when: ansible_distribution_release in ["horus"]
      register: elementary_os
      tags: ['always']
    - name: Debug ansible_distribution_release
      debug:
        msg: "{{ ansible_distribution_release }}"
      tags: ['always']

  tasks:
    - import_tasks: tasks/universe-repository.yml
      when: configure_universe_repository
      tags: ['universe-repository', 'extra-packages', 'extra-desktop-packages']
    # extra-packages should go after universe to ensure packages are found
    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages', 'extra-desktop-packages', 'skip-ci']
    - import_tasks: tasks/extra-desktop-packages.yml
      tags: ['extra-desktop-packages', 'skip-ci']
    - import_tasks: tasks/flatpak.yml
      tags: ['flatpak', 'skip-ci']
      when: configure_flatpak
    - import_tasks: tasks/snap.yml
      tags: ['snap', 'skip-ci']
      when: configure_snap
    - import_tasks: tasks/code-extensions.yml
      tags: ['code-extensions', 'skip-ci']
      when: configure_code_extensions
    - import_tasks: tasks/airpods-pro-bluetooth-fix.yml
      tags: ['airpods-pro-bluetooth-fix', 'skip-ci']
      when: configure_airpods_pro_bluetooth_fix
    - import_tasks: tasks/wifi-powersave-mode.yml
      tags: ['wifi-powersave-mode', 'skip-ci']
      when: configure_wifi_powersave_mode
    - import_tasks: tasks/deb/nordvpn.yml
      tags: ['nordvpn']
      when: configure_nordvpn
    - import_tasks: tasks/deb/stacer.yml
      tags: ['stacer']
      when: configure_stacer
    - import_tasks: tasks/deb/ulauncher.yml
      tags: ['ulauncher']
      when: configure_ulauncher
    - import_tasks: tasks/ppa/appimagelauncher.yml
      tags: ['appimagelauncher']
      become: true
      when: configure_appimagelauncher
    - import_tasks: tasks/nextcloud.yml
      tags: ['nextcloud']
      when: configure_nextcloud
    - import_tasks: tasks/ppa/caffeine.yml
      tags: ['caffeine']
      when: configure_caffeine
    - import_tasks: tasks/ppa/liquorix.yml
      tags: ['liquorix']
      when: configure_liquorix
    - import_tasks: tasks/ppa/terraform.yml
      tags: ['terraform']
      when: configure_terraform
    - import_tasks: tasks/ppa/timeshift.yml
      tags: ['timeshift']
      when: configure_timeshift
