---
- hosts: all
  # connection: local
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    # 'skip-ci' allows me to not test that role
    # 'never' is a special tag that is on run when that tag is specified

    # Terminal
    - {role: iancleary.zsh, tags: ['terminal', 'desktop', 'zsh', 'skip-ci']}
    - {role: zsh_fonts, tags: ['terminal', 'desktop', 'fonts']}
    - {role: iancleary.docker, tags: ['terminal', 'desktop', 'docker', 'skip-ci']}
    # - {role: python, tags: ['python']}
    - {role: iancleary.nodejs, tags: ['terminal', 'desktop', 'nodejs', 'npm', 'yarn']}
    - {role: terraform, tags: ['terminal', 'desktop', 'terraform']}
    - {role: iancleary.github_cli, tags: ['terminal', 'desktop', 'github-cli']}

    # Dotfiles
    - {role: iancleary.yadm, tags: ['dotfiles', 'yadm']}

    # Virtual Machine
    - {role: hyper-v, tags: ['vm', 'hyper-v', 'skip-ci']}

    # Desktop
    - {role: code, tags: ['desktop', 'init', 'code']}
    - {role: flatpak, tags: ['desktop', 'init', 'flatpak', 'skip-ci']}
    - {role: app-image, tags: ['desktop', 'init', 'app-image']}
    - {role: profile-sync-daemon, tags: ['desktop', 'init', 'profile-sync-daemon']}
    - {role: gnome-sushi, tags: ['desktop', 'init', 'gnome-sushi']}
    - {role: ulauncher, tags: ['desktop', 'init', 'ulauncher']}
    - {role: authy, tags: ['desktop', 'init', 'authy']}
    - {role: nordvpn, tags: ['desktop', 'nordvpn', 'skip-ci']}
    - {role: stacer, tags: ['desktop', 'stacer']}
    - {role: wifi-analyzer, tags: ['desktop', 'wifi-analyzer']}
    - {role: caffeine, tags: ['desktop', 'caffeine']}
    - {role: timeshift, tags: ['desktop', 'timeshift']}
    # Ubuntu 20.04 (Not Fedora -> Pipewire)
    - {role: pulseaudio, tags: ['desktop', 'pulseaudio']}

    # GNOME Desktop
    - {role: gnome-dash-to-dock, tags: ['never', 'gnome-desktop', 'gnome-dash-to-dock']}
    - {role: gnome-extensions, tags: ['never', 'gnome-desktop', 'gnome-extensions']}
    - {role: gnome-keybindings, tags: ['never', 'gnome-desktop', 'gnome-keybindings']}
    - {role: gnome-preferences, tags: ['never', 'gnome-desktop', 'gnome-preferences']}

    # Miscellaneous
    - {role: nautilus-mounts, tags: ['never', 'nautilus-mounts']}
    - {role: standard-notes, tags: ['never', 'common-snaps']}
    - {role: common-snaps, tags: ['never', 'common-snaps']}
    - {role: chat-clients, tags: ['never', 'chat-clients']}
    - {role: web-browsers, tags: ['never', 'web-browsers']}
    - {role: development-tools, tags: ['never', 'development-tools']}
    - {role: hyper, tags: ['never', 'hyper']}
