---
- hosts: all
  # connection: local
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    # 'skip-ci' allows me to not test that role
    # 'never' is a special tag that is on run when that tag is specified

    # Terminal
    - role: fonts
      when: configure_zsh
      tags: ['terminal', 'desktop', 'fonts']
    - role: zsh
      when: configure_zsh
      tags: ['terminal', 'desktop', 'zsh']
    - role: colorls
      when: configure_colorls
      tags: ['terminal', 'desktop', 'colorls']
      become: true
    - role: iancleary.docker
      when: configure_docker
      tags: ['terminal', 'desktop', 'docker', 'skip-ci']
      become: true
    - role: nodejs
      tags: ['terminal', 'desktop', 'nodejs', 'npm', 'yarn']
      become: true
    - role: github_cli
      when: configure_github_cli
      tags: ['terminal', 'desktop', 'github-cli', 'skip-ci']
    - role: iancleary.tailscale
      become: true
      when: configure_tailscale
      tags: ['terminal', 'desktop', 'tailscale', 'skip-ci']

    # Dotfiles
    - role: yadm
      tags: ['dotfiles', 'yadm']
      when: configure_dotfiles

    # Hyper-V Virtual Machine
    - role: hyper-v
      tags: ['vm', 'hyper-v', 'skip-ci']
      when: configure_hyper_v

    # Miscellaneous
    - role: nautilus-mounts
      tags: ['never', 'nautilus-mounts']
      when: configure_nautilus_mounts

    # Debug
    - role: debug
      tags: ['debug']

  tasks:
    - import_tasks: tasks/universe-repository.yml
      when: configure_universe_repository
      tags: ['universe-repository', 'extra-packages', 'extra-desktop-packages']
    # extra-packages should go after universe to ensure packages are found
    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages', 'extra-desktop-packages']
    - import_tasks: tasks/extra-desktop-packages.yml
      tags: ['extra-desktop-packages']
    - import_tasks: tasks/flatpak.yml
      tags: ['flatpak']
      when: configure_flatpak
    - import_tasks: tasks/snap.yml
      tags: ['snap']
      when: configure_snap
    - import_tasks: tasks/code-extensions.yml
      tags: ['code-extensions']
      when: configure_code_extensions
    - import_tasks: tasks/nextcloud.yml
      tags: ['nextcloud']
      when: configure_nextcloud
    - import_tasks: tasks/airpods-pro-bluetooth-fix.yml
      tags: ['airpods-pro-bluetooth-fix']
      when: configure_airpods_pro_bluetooth_fix
    - import_tasks: tasks/wifi-powersave-mode.yml
      tags: ['wifi-powersave-mode']
      when: configure_wifi_powersave_mode
    - import_tasks: tasks/deb/nordvpn.yml
      tags: ['nordvpn']
      when: configure_nordvpn
    - import_tasks: tasks/deb/stacer.yml
      tags: ['stacer']
      when: configure_stacer
    - import_tasks: tasks/deb/ulauncher.yml
      tags: ['ulauncher']
      when: configure_ulauncher
    - import_tasks: tasks/ppa/appimagelauncher.yml
      tags: ['appimagelauncher']
      become: true
      when: configure_appimagelauncher
    - import_tasks: tasks/ppa/caffeine.yml
      tags: ['caffeine']
      when: configure_caffeine
    - import_tasks: tasks/ppa/liquorix.yml
      tags: ['liquorix']
      when: configure_liquorix
    - import_tasks: tasks/ppa/terraform.yml
      tags: ['terraform']
      when: configure_terraform
    - import_tasks: tasks/ppa/timeshift.yml
      tags: ['timeshift']
      when: configure_timeshift
