---
- hosts: all
  # connection: local
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    # 'skip-ci' allows me to not test that role
    # 'never' is a special tag that is on run when that tag is specified

    # Terminal
    - role: fonts
      when: configure_zsh
      tags: ['terminal', 'desktop', 'fonts']
    - role: zsh
      when: configure_zsh
      tags: ['terminal', 'desktop', 'zsh']
    - role: colorls
      when: configure_colorls
      tags: ['terminal', 'desktop', 'colorls']
      become: true
    - role: docker
      when: configure_docker
      tags: ['terminal', 'desktop', 'docker', 'skip-ci']
      become: true
    # - {role: python, tags: ['python']}
    - role: nodejs
      tags: ['terminal', 'desktop', 'nodejs', 'npm', 'yarn']
      become: true
    - role: terraform
      when: configure_terraform
      tags: ['terminal', 'desktop', 'terraform']
    - role: github_cli
      when: configure_github_cli
      tags: ['terminal', 'desktop', 'github-cli']

    # Dotfiles
    - {role: yadm, tags: ['dotfiles', 'yadm']}

    # Virtual Machine
    - {role: hyper-v, tags: ['vm', 'hyper-v', 'skip-ci']}

    # Desktop
    - {role: app-image, tags: ['desktop', 'app-image']}
    - {role: code, tags: ['desktop', 'code']}
    - {role: flatpak, tags: ['desktop', 'flatpak', 'skip-ci']}
    - {role: snapd, tags: ['desktop', 'snapd', 'skip-ci']}

    - {role: nordvpn, tags: ['desktop', 'nordvpn', 'skip-ci']}
    - {role: stacer, tags: ['desktop', 'stacer']}
    - {role: wifi-analyzer, tags: ['desktop', 'wifi-analyzer']}
    - {role: caffeine, tags: ['desktop', 'caffeine']}
    - {role: timeshift, tags: ['desktop', 'timeshift']}
    # Ubuntu 20.04 (Not Fedora -> Pipewire)
    - {role: pulseaudio, tags: ['desktop', 'pulseaudio']}

    # Not desired on elementary OS 6 (dropped desktop tag)
    - {role: gnome-sushi, tags: ['gnome-sushi']}
    - {role: ulauncher, tags: ['ulauncher']}

    # Miscellaneous
    - {role: nautilus-mounts, tags: ['never', 'nautilus-mounts']}

    # Debug
    - {role: debug, tags: ['debug']}

  tasks:
    - import_tasks: tasks/universe-repository.yml
      when: configure_universe_repository
      tags: ['universe-repository', 'extra-packages']
    # extra-packages should go after universe to ensure packages are found
    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
    - import_tasks: tasks/flatpak.yml
      tags: ['flatpak']
      when: configure_flatpak
    - import_tasks: tasks/snap.yml
      tags: ['snap']
      when: configure_snap
    - import_tasks: tasks/code-extensions.yml
      tags: ['code-extensions']
      when: configure_code_extensions
    - import_tasks: tasks/ppa/appimagelauncher.yml
      tags: ['appimagelauncher']
      when: configure_code_extensions
