---
- name: Snaps - Install snapd apt dependency
  become: true
  apt:
    name: "snapd"
    state: present

- name: Common Snaps
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel | default('stable')}}"
    classic: "{{ item.classic | default('no')}}"
  with_items: "{{ snaps }}"

# https://github.com/ansible/ansible/issues/58403
# - name: Web Browsers - Setup Snap Plugs
#   become: "yes"
#   become_method: sudo
#   changed_when: false
#   shell: 'snap connect {{ item.app }}:{{ item.plug }}'
#   with_items: "{{ snaps_web_browsers_plugs }}"
