---
- name: Add appimagelauncher apt key.
  ansible.builtin.apt_key:
    url: >
      https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xacd802f535b6f55d365285574af9b16f75ef2fca
    id: "75ef2fca"
    keyring: /etc/apt/trusted.gpg.d/appimagelauncher.gpg
    state: present

- name: Add appimagelauncher repositories.
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - >-
      deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/appimagelauncher.gpg] https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu
        {{ ansible_distribution_release }} main
    - >-
      deb-src [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/appimagelauncher.gpg] https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu
        {{ ansible_distribution_release }} main
  register: appimagelauncher_repo

- name: Update apt cache if repo was added.
  ansible.builtin.apt:
    update_cache: "yes"
  when: appimagelauncher_repo.changed
  tags: ['skip_ansible_lint']

- name: Ensure appimagelauncher is installed.
  ansible.builtin.apt:
    name: "appimagelauncher"
    state: present
