---
- name: Install PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:caffeine-developers/ppa
    state: present

- name: Install apt package
  become: true
  ansible.builtin.apt:
    name: "caffeine"
    state: present
    update_cache: "yes"
