---
- name: Install snapd apt dependency
  become: true
  apt:
    name: "snapd"
    state: present

- name: Install Snaps
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel | default('stable')}}"
    classic: "{{ item.classic | default('no')}}"
  with_items: "{{ snaps }}"

# https://github.com/ansible/ansible/issues/58403
# I can't find a counterpart on https://github.com/ansible-collections/community.general/issues as of 2021-10-27
- name: Setup Snap Plugs
  become: "yes"
  become_method: sudo
  changed_when: false
  shell: 'snap connect {{ item.app }}:{{ item.plug }}'
  with_items: "{{ snap_plugs }}"
