---
- name: Install apt package
  ansible.builtin.apt:
    name: "ruby-full"
    state: present


- name: Install colorls gem and its dependencies
  community.general.gem:
    name: "{{ item }}"
    state: latest
    user_install : "no"
  loop:
    - colorls
    - addressable
    - public_suffix
    - clocale
    - filesize
    - manpages
    - rainbow
    - unicode-display_width

- name: Add tab_completion for colorls.
  ansible.builtin.template:
    src: colorls.sh.j2
    dest: /etc/profile.d/colorls.sh
    mode: '0644'
