---
- name: Nodejs - Ensure dependencies are present.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Nodejs - Add Nodesource apt key.
  ansible.builtin.apt_key:
    url: >
      https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    keyring: /etc/apt/trusted.gpg.d/node{{ nodejs_version|regex_replace('.x', '') }}.gpg
    state: present

- name: Nodejs - Add NodeSource repositories for Node.js.
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - >-
      deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/node{{ nodejs_version|regex_replace('.x', '') }}.gpg] https://deb.nodesource.com/node_{{ nodejs_version }}
        {{ ansible_distribution_release }} main
    - >-
      deb-src [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/node{{ nodejs_version|regex_replace('.x', '') }}.gpg] https://deb.nodesource.com/node_{{ nodejs_version }}
        {{ ansible_distribution_release }} main
  register: node_repo

- name: Nodejs - Update apt cache if repo was added.
  ansible.builtin.apt:
    update_cache: "yes"
  when: node_repo.changed
  tags: ['skip_ansible_lint']

- name: Nodejs - Ensure Node.js is installed.
  ansible.builtin.apt:
    name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present
